theme: jekyll-theme-minimal
title: 'UC Davis Slurm Workshop'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: base/welcome

  - heading: Slurm
  - title: Intro
    url: cluster_training/intro
  - title: LSSC0
    url: cluster_training/lssc0_onboard
  - title: Modules
    url: cluster_training/modules
  - title: Priority
    url: cluster_training/priority
  - title: Q Commands
    url: cluster_training/q_commands
  - title: Rules
    url: cluster_training/rules
  - title: S Commands
    url: cluster_training/s_commands
  - title: Scheduler
    url: cluster_training/scheduler
  - title: Transfer
    url: cluster_training/transfer


